# Generated by Django 3.1.7 on 2021-04-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
