# Generated by Django 3.1.7 on 2021-04-27 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='num_joins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Request_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to='Wingman.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
