# Generated by Django 3.1.7 on 2021-04-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0006_request_joined_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_joined_list',
            old_name='request',
            new_name='req',
        ),
    ]
