# Generated by Django 3.1.7 on 2021-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0007_auto_20210427_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_joined_list',
            old_name='req',
            new_name='request',
        ),
    ]
