# Generated by Django 3.1.7 on 2021-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0012_auto_20210501_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
