# Generated by Django 3.1.7 on 2021-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0013_auto_20210501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='del_corp',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
