# Generated by Django 3.1.7 on 2021-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0014_auto_20210501_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='detail_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='arrive_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
