# Generated by Django 3.1.7 on 2021-05-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0015_auto_20210501_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(default='未指定', max_length=32),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='Wingman.del_status'),
        ),
    ]
