# Generated by Django 3.1.7 on 2021-05-01 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0017_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
