# Generated by Django 3.1.7 on 2021-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wingman', '0022_auto_20210502_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='announcement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='chatting',
            name='top',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/default.png', upload_to=''),
        ),
    ]
